fixed with simple array input functions
quantanet/solidity-examples pull request #11
Opened 2019-10-24 06:56 UTC by Soumyanil

fixed few of the functions with right conventions and right return from function

2019-10-24 08:53 UTC, asabya commented on Arrays/arraySample.sol
> +    uint[3] fixedSimpleArr;  // fixed sized normal array
An array is by default 1D array. Please remove `normal`. You can write something like this `array of fixed size` @Soumyanil

2019-10-24 08:54 UTC, asabya commented on Arrays/arraySample.sol
> +    uint[] simpleDynamicArr; // dynamic normal array
`dynamic array` is more effective

2019-10-25 11:59 UTC, 0mkara requested changes

2019-10-25 11:59 UTC, 0mkara commented on Arrays/arraySample.sol
> +    uint[3] fixedSimpleArr;  // array of fix size
`// fixed sized array`

2019-10-25 11:59 UTC, 0mkara commented on Arrays/arraySample.sol
>      uint[3][3] fixedSized;   // fixed sized array
`fixed sized 2D array`

2019-10-25 11:59 UTC, 0mkara commented on Arrays/arraySample.sol
> +    function getFixedSimpleArr() public view returns (uint[3] memory){
Space after parenthesis. `) {`

2019-10-25 18:57 UTC, 0mkara approved these changes

2019-10-25 18:58 UTC, merged